# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: win_counts/winner.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17win_counts/winner.proto\x12\x06winner\"\x1f\n\rWinnerRequest\x12\x0e\n\x06winner\x18\x01 \x01(\t\"<\n\x0eWinnerResponse\x12\x0e\n\x06police\x18\x01 \x01(\x05\x12\r\n\x05thief\x18\x02 \x01(\x05\x12\x0b\n\x03tie\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'win_counts.winner_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WINNERREQUEST._serialized_start=35
  _WINNERREQUEST._serialized_end=66
  _WINNERRESPONSE._serialized_start=68
  _WINNERRESPONSE._serialized_end=128
# @@protoc_insertion_point(module_scope)
